# Generated by Django 4.1.1 on 2022-10-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alldata',
            fields=[
                ('idalldata', models.AutoField(db_column='idAllData', primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
                ('changeableprice', models.FloatField(db_column='changeablePrice')),
                ('installmentprice', models.CharField(db_column='installmentPrice', max_length=1000)),
                ('changeableinstallmentprice', models.FloatField(db_column='changeableInstallmentPrice')),
                ('link', models.CharField(db_column='Link', max_length=1000)),
                ('image', models.CharField(db_column='Image', max_length=1000)),
                ('time', models.CharField(db_column='Time', max_length=1000)),
                ('logo', models.CharField(db_column='Logo', max_length=1000)),
                ('type', models.CharField(db_column='Type', max_length=1000)),
                ('model', models.CharField(db_column='Model', max_length=1000)),
                ('format', models.CharField(blank=True, db_column='Format', max_length=1000, null=True)),
                ('interface', models.CharField(blank=True, db_column='Interface', max_length=1000, null=True)),
                ('capacity', models.CharField(blank=True, db_column='Capacity', max_length=1000, null=True)),
                ('ddr', models.CharField(blank=True, db_column='DDR', max_length=1000, null=True)),
                ('frequency', models.CharField(blank=True, db_column='Frequency', max_length=1000, null=True)),
                ('platform', models.CharField(blank=True, db_column='Platform', max_length=1000, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'alldata',
                'managed': False,
            },
        ),
    ]
